--- 1 ---
SELECT DISTINCT NAME AS name
FROM STARSIN, MOVIESTAR
WHERE (NAME = STARNAME AND MOVIETITLE = 'The Usual Suspects' AND GENDER = 'M')

--- 2 ---
SELECT STARNAME
FROM STARSIN, MOVIE
WHERE YEAR = 1995 AND STUDIONAME = 'MGM' AND MOVIETITLE = TITLE

--- 3 --- 
SELECT DISTINCT NAME AS name
FROM MOVIEEXEC, MOVIE 
WHERE STUDIONAME = 'MGM' AND CERT# = PRODUCERC# 

--- 4 ---
SELECT TITLE AS title
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH 
FROM MOVIE
WHERE TITLE = 'Star wars')

--- 5 ---
SELECT NAME 
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH
FROM MOVIEEXEC
WHERE NAME = 'Stephen Spielberg')

