--- 1 ---
SELECT NAME
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND DISPLACEMENT > 50000

--- 2 ---
SELECT DISTINCT NAME,DISPLACEMENT,NUMGUNS
FROM CLASSES, SHIPS,OUTCOMES
WHERE BATTLE = 'Guadalcanal' AND NAME = SHIP AND SHIPS.CLASS = CLASSES.CLASS

--- 3 ---
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc'

--- 4 ---
SELECT DISTINCT O1.SHIP
FROM BATTLES AS B1,BATTLES AS B2, OUTCOMES AS O1,OUTCOMES AS O2
WHERE B1.DATE < B2.DATE
AND O1.RESULT = 'damaged' AND O1.BATTLE = B1.NAME
AND O2.BATTLE = B2.NAME AND O1.SHIP = O2.SHIP