--- 1 --
SELECT NAME,TITLE
FROM MOVIE JOIN MOVIEEXEC
ON PRODUCERC# = CERT#
WHERE NAME = (
SELECT DISTINCT NAME 
FROM MOVIE JOIN MOVIEEXEC
ON PRODUCERC# = CERT#
WHERE TITLE = 'Star Wars')

--- 2 ---
SELECT DISTINCT NAME
FROM MOVIEEXEC,
(SELECT TITLE,PRODUCERC#
FROM MOVIE JOIN STARSIN
ON TITLE = MOVIETITLE
WHERE STARNAME = 'Harrison Ford') COMB
WHERE MOVIEEXEC.CERT# = COMB.PRODUCERC#

--- 3 ---
SELECT DISTINCT STUDIONAME,STARNAME
FROM MOVIE JOIN STARSIN
ON TITLE = MOVIETITLE
ORDER BY STUDIONAME

--- 4 ---
SELECT DISTINCT STARNAME,NETWORTH,TITLE
FROM STARSIN,
(SELECT DISTINCT NETWORTH,TITLE
FROM MOVIE JOIN MOVIEEXEC
ON CERT# = PRODUCERC#
WHERE NETWORTH >= ALL(SELECT DISTINCT NETWORTH FROM MOVIEEXEC)) NETS
WHERE MOVIETITLE = TITLE

--- 5 ---
SELECT NAME
FROM MOVIESTAR LEFT JOIN STARSIN
ON STARNAME = NAME
WHERE MOVIETITLE IS NULL