--- 1 ---
SELECT *
FROM SHIPS JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.NAME IS NOT NULL

--- 2 ---
SELECT *
FROM SHIPS
FULL JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS
WHERE CLASSES.CLASS IS NOT NULL OR CLASSES.CLASS IN (SELECT NAME FROM SHIPS)

--- 3 ---
SELECT COUNTRY,NAME
FROM (SELECT COUNTRY,NAME
FROM CLASSES JOIN SHIPS
ON CLASSES.CLASS = SHIPS.CLASS) s LEFT JOIN OUTCOMES
ON s.NAME = OUTCOMES.SHIP
WHERE BATTLE IS NULL

--- 4 ---
SELECT NAME AS 'Ship name'
FROM SHIPS JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS
WHERE LAUNCHED = 1916 AND NUMGUNS >= 7

--- 5 ---
SELECT NAME,BATTLE,DATE
FROM (SELECT NAME,DISPLACEMENT
FROM SHIPS JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS) C FULL JOIN (SELECT SHIP,DATE,RESULT,BATTLE FROM BATTLES JOIN OUTCOMES ON BATTLE = NAME) B
ON C.NAME = B.SHIP
WHERE B.RESULT = 'sunk'
ORDER BY BATTLE

--- 6 ---
SELECT NAME,DISPLACEMENT,LAUNCHED
FROM SHIPS JOIN CLASSES
ON CLASSES.CLASS = SHIPS.CLASS 
AND CLASSES.CLASS = SHIPS.NAME

--- 7 ---
SELECT *
FROM CLASSES
WHERE CLASSES.CLASS NOT IN(SELECT CLASSES.CLASS FROM SHIPS JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS)

--- 8 ---
SELECT NAME,DISPLACEMENT,NUMGUNS,RESULT
FROM SHIPS JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS JOIN OUTCOMES ON OUTCOMES.SHIP = NAME
WHERE BATTLE = 'North Atlantic'