--- 1 ---
SELECT MOVIESTAR.NAME, NETWORTH
FROM MOVIESTAR JOIN MOVIEEXEC
	 ON MOVIESTAR.NAME = MOVIEEXEC.NAME
WHERE NETWORTH > 10000000

--- 2 ---
SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN (SELECT NAME 
					FROM MOVIEEXEC)

--- 3 ---
SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH
				FROM MOVIE
				WHERE TITLE = 'Star Wars')

--- 4 ---
SELECT TITLE,NAME
FROM MOVIE JOIN MOVIEEXEC
	ON PRODUCERC# = CERT#
WHERE NETWORTH > (SELECT NETWORTH
					FROM MOVIEEXEC
					WHERE NAME = 'Merv Griffin')
