--- 1 ---
CREATE VIEW v_reservedFlight AS
SELECT AIRLINE_OPERATOR, FNUMBER, COUNT(BOOKINGS.CUSTOMER_ID) AS CUSTOMER_COUNT
FROM FLIGHTS LEFT JOIN BOOKINGS
ON FLIGHT_NUMBER = FNUMBER
GROUP BY FNUMBER,AIRLINE_OPERATOR

SELECT * FROM v_reservedFlight

--- 2 ---

CREATE VIEW V_mostBookings AS
SELECT CUSTOMERS.FNAME, CUSTOMERS.LNAME, CUSTOMERS.ID
FROM CUSTOMERS WHERE (ID IN (SELECT CUSTOMER_ID FROM BOOKINGS AS b
GROUP BY AGENCY, CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) >=
(SELECT TOP 1 COUNT(CUSTOMER_ID) FROM BOOKINGS WHERE BOOKINGS.AGENCY = b.AGENCY
GROUP BY AGENCY, CUSTOMER_ID
ORDER BY COUNT(CUSTOMER_ID) DESC)))


SELECT * FROM V_mostBookings

--- 3 ---
CREATE VIEW v_agencies AS
SELECT *
FROM AGENCIES
WHERE CITY = 'Sofia'
WITH CHECK OPTION;

SELECT * FROM v_agencies

--- 4 ---
CREATE VIEW v_agenciesNull AS
SELECT *
FROM AGENCIES
WHERE PHONE IS NULL
WITH CHECK OPTION;


SELECT * FROM v_agenciesNull
